CC := gcc
fopen_test: fopen.c
	-$(CC)  $^ -o $@
	-./$@
	-rm  $@
fclose_test: fclose.c
	-$(CC)  $^ -o $@
	-./$@
	-rm  $@
fputc_test:fputc.c
	-$(CC) $^ -o $@
	-./$@
	-rm ./$@
fputs_teet:fputs.c
	-$(CC) $^ -o $@
	-./$@
	-rm ./$@
fprintf_teet:fprintf.c
	-$(CC) $^ -o $@
	-./$@
	-rm ./$@
fgetc_test:fgetc.c
	-$(CC) $^ -o $@
	-./$@
	-rm ./$@
fgets_test:fgets.c
	-$(CC) $^ -o $@
	-./$@
	-rm ./$@
fscanf_test:fscanf.c
	-$(CC) $^ -o $@
	-./$@
	-rm ./$@
stdin_out_error:stdin_out_error.c
	-$(CC) $^ -o $@
	-./$@
	-rm ./$@
