CC:=gcc
openR: open.c
	-$(CC) $^ -o $@
	-./$@
	-rm $@
hello: hello_argc.c
	-$(CC) $^ -o $@
	-./$@
	-rm $@
execve: execev.c
	-$(CC) $^ -o $@
	-./$@
	-rm $@
fork_execve: fork_execve.c
	-$(CC) $^ -o $@
	-./$@
	-rm $@